#!/bin/bash

echo "🚀 Preparando despliegue en Easypanel..."
echo ""
echo "📋 Pasos para completar el despliegue:"
echo ""
echo "1. Sube el código a GitHub:"
echo "   git remote add origin https://github.com/TU_USUARIO/dominican-domino.git"
echo "   git push -u origin main"
echo ""
echo "2. En Easypanel (https://easypanel.io):"
echo "   - Crea un nuevo proyecto"
echo "   - Conecta tu repositorio de GitHub"
echo "   - Selecciona 'Dockerfile' como tipo de build"
echo ""
echo "3. Configuración en Easypanel:"
echo "   - Puerto: 3001"
echo "   - Health Check Path: /"
echo "   - Variables de entorno:"
echo "     NODE_ENV=production"
echo "     PORT=3001"
echo ""
echo "4. Dominio personalizado (opcional):"
echo "   - Agrega tu dominio en la configuración"
echo "   - Easypanel generará certificado SSL automáticamente"
echo ""
echo "✅ El proyecto está listo para desplegar!"
echo ""
echo "📱 Una vez desplegado, tu juego estará disponible en:"
echo "   https://tu-proyecto.on-easypanel.com"
echo "   o en tu dominio personalizado"
echo ""